name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        
      - name: Compile Latex Documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            resume/resume.tex
            cover-letter/coverletter.tex
        env:
          TEXINPUTS: ".:./resume//:./cover-letter//:"
          
      - name: Create Release
        uses: docker://ghcr.io/anton-yurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
            *.log
            *.pdf
